version: '3'
services:
  write-service:
    build:
      context: .
      dockerfile: WriteService/Dockerfile  # Specify the path to WriteService's Dockerfile
    ports:
      - "5000:80"  # Adjust the port as needed
    depends_on:
      - postgres
      - rabbitmq

  read-service:
    build:
      context: .
      dockerfile: ReadService/Dockerfile  # Specify the path to WriteService's Dockerfile
    ports:
      - "5001:80"  # Adjust the port as needed
    depends_on:
      - mongodb
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"  # RabbitMQ management console
      - "5672:5672"

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: cqrs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  postgres_data: